tools: make: package: Adapt AnyKernel3 for Mint
Signed-off-by: Louis Poier <lpoier7@proton.me>

diff --git a/tools/make/package/META-INF/com/google/android/update-binary b/tools/make/package/META-INF/com/google/android/update-binary
--- a/tools/make/package/META-INF/com/google/android/update-binary
+++ b/tools/make/package/META-INF/com/google/android/update-binary
@@ -292,22 +292,22 @@ abort() {
 do_devicecheck() {
   [ "$(file_getprop anykernel.sh do.devicecheck)" == 1 ] || return 1;
   local device devicename match product testname vendordevice vendorproduct;
-  ui_print "Checking device...";
+  ui_print "  - Checking device...";
   device=$(getprop ro.product.device 2>/dev/null);
   product=$(getprop ro.build.product 2>/dev/null);
   vendordevice=$(getprop ro.product.vendor.device 2>/dev/null);
   vendorproduct=$(getprop ro.vendor.product.device 2>/dev/null);
-  for testname in $(grep '^device.name.*=' anykernel.sh | cut -d= -f2-); do
+  for testname in $(grep '^ro.mint.device.name.*=' mint.prop | cut -d= -f2-); do
     for devicename in $device $product $vendordevice $vendorproduct; do
       if [ "$devicename" == "$testname" ]; then
-        ui_print "$testname" " ";
+        ui_print "    - $testname";
         match=1;
         break 2;
       fi;
     done;
   done;
   if [ ! "$match" ]; then
-    abort " " "Unsupported device. Aborting...";
+    abort "    - Unsupported device. Aborting...";
   fi;
 }
 int2ver() {
@@ -322,8 +322,8 @@ int2ver() {
 do_versioncheck() {
   [ "$(file_getprop anykernel.sh supported.versions)" ] || return 1;
   local android_ver hi_ver lo_ver parsed_ver supported supported_ver;
-  ui_print "Checking Android version...";
-  supported_ver=$(file_getprop anykernel.sh supported.versions | tr -d '[:space:]');
+  ui_print "  - Checking Android version...";
+  supported_ver=$(file_getprop mint.prop ro.mint.droid.platform | tr -d '[:space:]');
   android_ver=$(file_getprop /system/build.prop ro.build.version.release);
   parsed_ver=$(int2ver $android_ver);
   if echo $supported_ver | grep -q '-'; then
@@ -341,15 +341,45 @@ do_versioncheck() {
     done;
   fi;
   if [ "$supported" ]; then
-    ui_print "$android_ver" " ";
+    ui_print "    - Android $android_ver";
   else
-    abort " " "Unsupported Android version. Aborting...";
+    ui_print "    - Warning: Android version doesn't match supported version!";
+    ui_print "      Make sure you have downloaded the correct version of Mint.";
+    ui_print "      Proceeding to install...";
+  fi;
+}
+do_variantcheck() {
+  [ "$(file_getprop mint.prop ro.mint.droid.variant)" ] || return 1;
+  local oneui platform kernel_platform supported;
+  ui_print "  - Checking kernel variant...";
+  oneui=$(file_getprop "/system_root/system/build.prop" "ro.build.PDA");
+  kernel_platform=$(file_getprop mint.prop ro.mint.droid.variant | $BB tr 'A-Z' 'a-z');
+
+  # If ro.build.PDA is not blank, it's a One UI ROM.
+  if [ ! -z $oneui ]; then
+    platform=oneui
+  else
+    platform=aosp
+  fi
+
+  if [ "$kernel_platform" == "$platform" ]; then
+    supported=1;
+  fi;
+
+  if [ "$supported" ]; then
+    ui_print "    - Your current ROM is: ${platform}";
+  else
+    ui_print "    - Error: This Mint build is for ${kernel_platform}!";
+    ui_print "      Your current ROM is: ${platform}" " ";
+    ui_print "      Check if you have downloaded the correct";
+    ui_print "      version for the ROM you have installed." " ";
+    abort "      Aborting installation...";
   fi;
 }
 do_levelcheck() {
   [ "$(file_getprop anykernel.sh supported.patchlevels)" ] || return 1;
   local android_lvl hi_lvl lo_lvl parsed_lvl supported_lvl;
-  ui_print "Checking Android security patch level...";
+  ui_print "  - Checking Android security patch level...";
   supported_lvl=$(file_getprop anykernel.sh supported.patchlevels | grep -oE '[0-9]{4}-[0-9]{2}|-');
   android_lvl=$(file_getprop /system/build.prop ro.build.version.security_patch);
   parsed_lvl=$(echo $android_lvl | grep -oE '[0-9]{4}-[0-9]{2}');
@@ -363,10 +393,10 @@ do_levelcheck() {
     lo_lvl=$(echo $supported_lvl | awk '{ print $1 }');
     hi_lvl=9999-99;
   fi;
-  if echo -e "$hi_lvl\n$lo_lvl\n$parsed_lvl" | sort -g | grep -n "$parsed_lvl" | grep -q '^2:'; then
-    ui_print "$android_lvl" " ";
+  if echo -e "$hi_lvl\n$lo_lvl\n$parsed_lvl" | $BB sort -g | $BB grep -n "$parsed_lvl" | $BB grep -q '^2:'; then
+    ui_print "    - $android_lvl" " ";
   else
-    abort " " "Unsupported Android security patch level. Aborting...";
+    abort "    - Unsupported Android security patch level. Aborting...";
   fi;
 }
 do_vendorlevelcheck() {
@@ -523,7 +553,7 @@ do_modules() {
   cd $AKHOME;
 }
 
-show_progress 1.34 25;
+show_progress 1.34 13;
 ui_print " ";
 cleanup;
 mkdir -p $AKHOME/bin;
@@ -539,9 +569,19 @@ fi;
 OLD_PATH="$PATH";
 export PATH="$AKHOME/tools:$AKHOME/bin:$PATH";
 
+KERNEL_VARIANT="$(file_getprop mint.prop ro.mint.droid.variant)";
+KERNEL_BRANCH="$(file_getprop mint.prop ro.mint.build.branch)";
+KERNEL_ANDROID="$(file_getprop mint.prop ro.mint.droid.android)";
+KERNEL_BETA="$(file_getprop mint.prop ro.mint.droid.beta)";
+
 if [ -f banner ]; then
   ui_printfile banner;
-  ui_print " " " ";
+  ui_print "          Mint variant: $KERNEL_VARIANT";
+  ui_print "       Android version: Android $KERNEL_ANDROID";
+  if [ "$KERNEL_BETA" == 'true' ]; then
+    ui_print "           Base branch: $KERNEL_BRANCH";
+  fi
+  ui_print " ";
 fi;
 
 KERNEL_STRING="$(file_getprop anykernel.sh kernel.string)";
@@ -557,13 +597,23 @@ ui_print " ";
 
 setup_env;
 
+ui_print " " "- Preparing for installation..."
 do_devicecheck;
 do_versioncheck;
+do_variantcheck;
 do_levelcheck;
-do_vendorlevelcheck;
 
-ui_print "Installing...";
-# hack to maintain support for anykernel.sh files that weren't updated correctly along with the AK core
+KERNEL_BUILD="$(file_getprop mint.prop ro.mint.build.version)";
+KERNEL_DEVICE="$(file_getprop mint.prop ro.mint.droid.device)";
+
+if [ "$KERNEL_BETA" == 'true' ]; then
+  ui_print "- Installing Mint Kernel Beta - Build ${KERNEL_BUILD}";
+else
+  ui_print "- Installing Mint Kernel Stable - v$KERNEL_BUILD";
+fi
+
+ui_print "  for the Galaxy $KERNEL_DEVICE...";
+
 CORE=$(grep -oE 'ak.*core.sh' anykernel.sh);
 [ -f tools/$CORE ] || ln -s $AKHOME/tools/ak*-core.sh $AKHOME/tools/$CORE;
 ash anykernel.sh;
@@ -581,6 +631,6 @@ if [ "$(file_getprop anykernel.sh do.cleanup)" == 1 ]; then
   cleanup;
 fi;
 
-ui_print " " "Done!";
+ui_print " " "- Installation complete!" " ";
 export PATH="$OLD_PATH";
 unset OLD_PATH OUTFD ZIPFILE;
